export const offlinePhrases = [
  {
    id: 'general-hello',
    category: 'general',
    frenchVariants: ["bonjour", "salut"],
    americanEnglishText: 'Hi.',
    frenchMeaning: 'Bonjour.',
    keywords: ["bonjour", "bonjour.", "general", "salut"],
    priority: 10,
  },
  {
    id: 'general-good-evening-how-are-you',
    category: 'general',
    frenchVariants: ["bonsoir comment allez-vous", "bonsoir comment allez vous"],
    americanEnglishText: 'Good evening, how are you doing?',
    frenchMeaning: 'Bonsoir, comment allez-vous ?',
    keywords: ["bonsoir", "comment", "allez"],
    priority: 10,
  },
  {
    id: 'general-how-are-you-no-hello',
    category: 'general',
    frenchVariants: ["comment allez-vous", "comment allez vous"],
    americanEnglishText: 'How are you doing?',
    frenchMeaning: 'Comment allez-vous ?',
    keywords: ["comment", "allez"],
    priority: 10,
  },
  {
    id: 'general-how-are-you',
    category: 'general',
    frenchVariants: ["bonjour comment allez-vous", "comment allez-vous"],
    americanEnglishText: 'Hi, how are you doing?',
    frenchMeaning: 'Bonjour, comment allez-vous ?',
    keywords: ["allez-vous", "bonjour", "comment", "general"],
    priority: 9,
  },
  {
    id: 'general-hello-hope-well',
    category: 'general',
    frenchVariants: ["bonjour j’espère que tout va bien pour vous", "bonjour j’espère que vous allez bien", "salut j’espère que vous allez bien"],
    americanEnglishText: 'Hi, I hope you’re doing well.',
    frenchMeaning: 'Bonjour, j’espère que vous allez bien.',
    keywords: ["bonjour", "espere", "bien", "vous"],
    priority: 10,
  },
  {
    id: 'general-good-evening',
    category: 'general',
    frenchVariants: ["bonsoir"],
    americanEnglishText: 'Good evening.',
    frenchMeaning: 'Bonsoir.',
    keywords: ["bonsoir", "soir"],
    priority: 10,
  },
  {
    id: 'general-hope-well',
    category: 'general',
    frenchVariants: ["j’espère que vous allez bien", "j’espère que tout va bien pour vous", "bonjour j’espère que tout va bien pour vous", "bonjour j’espère que vous allez bien"],
    americanEnglishText: 'I hope you’re doing well.',
    frenchMeaning: 'J’espère que vous allez bien.',
    keywords: ["allez", "bien", "bien.", "bonjour", "espère", "general", "j", "pour", "que", "tout"],
    priority: 8,
  },
  {
    id: 'general-french-poor-english',
    category: 'general',
    frenchVariants: ["je suis français je ne parle pas bien anglais", "je suis française je ne parle pas bien anglais"],
    americanEnglishText: 'I’m French. I don’t speak English very well.',
    frenchMeaning: 'Je suis français, je ne parle pas bien anglais.',
    keywords: ["anglais", "anglais.", "bien", "français", "française", "general", "je", "ne", "parle", "pas"],
    priority: 7,
  },
  {
    id: 'general-repeat-slowly',
    category: 'general',
    frenchVariants: ["pouvez-vous répéter lentement", "pouvez-vous répéter lentement s’il vous plaît"],
    americanEnglishText: 'Could you repeat that slowly, please?',
    frenchMeaning: 'Pouvez-vous répéter lentement, s’il vous plaît ?',
    keywords: ["general", "il", "lentement", "plaît", "pouvez-vous", "répéter", "s", "vous"],
    priority: 6,
  },
  {
    id: 'general-write-down',
    category: 'general',
    frenchVariants: ["pouvez-vous écrire ça", "vous pouvez écrire ça"],
    americanEnglishText: 'Could you write that down, please?',
    frenchMeaning: 'Pouvez-vous écrire ça ?',
    keywords: ["general", "pouvez", "pouvez-vous", "vous", "ça", "écrire"],
    priority: 5,
  },
  {
    id: 'general-dont-understand',
    category: 'general',
    frenchVariants: ["je ne comprends pas", "je comprends pas"],
    americanEnglishText: 'I don’t understand.',
    frenchMeaning: 'Je ne comprends pas.',
    keywords: ["comprends", "general", "je", "ne", "pas", "pas."],
    priority: 4,
  },
  {
    id: 'general-help',
    category: 'general',
    frenchVariants: ["pouvez-vous m’aider", "est-ce que vous pouvez m’aider"],
    americanEnglishText: 'Can you help me, please?',
    frenchMeaning: 'Pouvez-vous m’aider ?',
    keywords: ["aider", "est-ce", "general", "m", "pouvez", "pouvez-vous", "que", "vous"],
    priority: 3,
  },
  {
    id: 'general-hope-everything-well',
    category: 'general',
    frenchVariants: ["j’espère que tout va bien"],
    americanEnglishText: 'I hope everything is going well.',
    frenchMeaning: 'J’espère que tout va bien.',
    keywords: ["espere", "tout", "bien"],
    priority: 10,
  },
  {
    id: 'general-thank-you',
    category: 'general',
    frenchVariants: ["merci", "je vous remercie"],
    americanEnglishText: 'Thank you.',
    frenchMeaning: 'Merci.',
    keywords: ["general", "je", "merci", "merci.", "remercie", "vous"],
    priority: 2,
  },
  {
    id: 'general-thanks-help',
    category: 'general',
    frenchVariants: ["merci pour votre aide"],
    americanEnglishText: 'Thank you for your help.',
    frenchMeaning: 'Merci pour votre aide.',
    keywords: ["aide", "aide.", "general", "merci", "pour", "votre"],
    priority: 1,
  },
  {
    id: 'general-thank-you-very-much',
    category: 'general',
    frenchVariants: ["merci beaucoup"],
    americanEnglishText: 'Thank you very much.',
    frenchMeaning: 'Merci beaucoup.',
    keywords: ["merci", "beaucoup"],
    priority: 10,
  },
  {
    id: 'general-goodbye',
    category: 'general',
    frenchVariants: ["au revoir"],
    americanEnglishText: 'Goodbye.',
    frenchMeaning: 'Au revoir.',
    keywords: ["au", "general", "revoir", "revoir."],
    priority: 1,
  },
  {
    id: 'general-yes',
    category: 'general',
    frenchVariants: ["oui"],
    americanEnglishText: 'Yes.',
    frenchMeaning: 'Oui.',
    keywords: ["general", "oui", "oui."],
    priority: 1,
  },
  {
    id: 'general-no',
    category: 'general',
    frenchVariants: ["non"],
    americanEnglishText: 'No.',
    frenchMeaning: 'Non.',
    keywords: ["general", "non", "non."],
    priority: 1,
  },
  {
    id: 'general-sorry',
    category: 'general',
    frenchVariants: ["désolé", "excusez-moi"],
    americanEnglishText: 'Sorry.',
    frenchMeaning: 'Désolé.',
    keywords: ["désolé", "désolé.", "excusez-moi", "general"],
    priority: 1,
  },
  {
    id: 'general-one-moment',
    category: 'general',
    frenchVariants: ["un instant s’il vous plaît"],
    americanEnglishText: 'One moment, please.',
    frenchMeaning: 'Un instant, s’il vous plaît.',
    keywords: ["general", "il", "instant", "plaît", "plaît.", "s", "un", "vous"],
    priority: 1,
  },
  {
    id: 'general-phone-translate',
    category: 'general',
    frenchVariants: ["j’utilise une application de traduction"],
    americanEnglishText: 'I’m using a translation app.',
    frenchMeaning: 'J’utilise une application de traduction.',
    keywords: ["application", "de", "general", "j", "traduction", "traduction.", "une", "utilise"],
    priority: 1,
  },
  {
    id: 'general-speak-french',
    category: 'general',
    frenchVariants: ["parlez-vous français"],
    americanEnglishText: 'Do you speak French?',
    frenchMeaning: 'Parlez-vous français ?',
    keywords: ["français", "general", "parlez-vous"],
    priority: 1,
  },
  {
    id: 'general-not-sure',
    category: 'general',
    frenchVariants: ["je ne suis pas sûr"],
    americanEnglishText: 'I’m not sure.',
    frenchMeaning: 'Je ne suis pas sûr.',
    keywords: ["general", "je", "ne", "pas", "suis", "sûr", "sûr."],
    priority: 1,
  },
  {
    id: 'restaurant-check',
    category: 'restaurant',
    frenchVariants: ["je voudrais payer l’addition", "je voudrais l’addition s’il vous plaît", "l’addition s’il vous plaît", "je peux avoir l’addition"],
    americanEnglishText: 'Can I get the check, please?',
    frenchMeaning: 'Je voudrais l’addition, s’il vous plaît.',
    keywords: ["addition", "avoir", "il", "je", "l", "payer", "peux", "plaît", "plaît.", "restaurant"],
    priority: 1,
  },
  {
    id: 'restaurant-restroom',
    category: 'restaurant',
    frenchVariants: ["où sont les toilettes", "où est les toilettes"],
    americanEnglishText: 'Where’s the restroom?',
    frenchMeaning: 'Où sont les toilettes ?',
    keywords: ["est", "les", "où", "restaurant", "sont", "toilettes"],
    priority: 1,
  },
  {
    id: 'restaurant-water',
    category: 'restaurant',
    frenchVariants: ["je voudrais de l’eau", "je voudrais de l’eau s’il vous plaît"],
    americanEnglishText: 'Can I get some water, please?',
    frenchMeaning: 'Je voudrais de l’eau.',
    keywords: ["de", "eau", "eau.", "il", "je", "l", "plaît", "restaurant", "s", "voudrais"],
    priority: 1,
  },
  {
    id: 'restaurant-table-three',
    category: 'restaurant',
    frenchVariants: ["je voudrais une table pour trois personnes"],
    americanEnglishText: 'Can we get a table for three, please?',
    frenchMeaning: 'Je voudrais une table pour trois personnes.',
    keywords: ["je", "personnes", "personnes.", "pour", "restaurant", "table", "trois", "une", "voudrais"],
    priority: 1,
  },
  {
    id: 'restaurant-tip-included',
    category: 'restaurant',
    frenchVariants: ["est-ce que le service est compris", "est-ce que le pourboire est inclus"],
    americanEnglishText: 'Is the tip included?',
    frenchMeaning: 'Est-ce que le service est compris ?',
    keywords: ["compris", "est", "est-ce", "inclus", "le", "pourboire", "que", "restaurant", "service"],
    priority: 1,
  },
  {
    id: 'restaurant-menu',
    category: 'restaurant',
    frenchVariants: ["puis-je avoir le menu"],
    americanEnglishText: 'Can I see the menu, please?',
    frenchMeaning: 'Puis-je avoir le menu ?',
    keywords: ["avoir", "le", "menu", "puis-je", "restaurant"],
    priority: 1,
  },
  {
    id: 'restaurant-order',
    category: 'restaurant',
    frenchVariants: ["je voudrais commander"],
    americanEnglishText: 'I’d like to order, please.',
    frenchMeaning: 'Je voudrais commander.',
    keywords: ["commander", "commander.", "je", "restaurant", "voudrais"],
    priority: 1,
  },
  {
    id: 'restaurant-coffee',
    category: 'restaurant',
    frenchVariants: ["je voudrais un café"],
    americanEnglishText: 'Can I get a coffee, please?',
    frenchMeaning: 'Je voudrais un café.',
    keywords: ["café", "café.", "je", "restaurant", "un", "voudrais"],
    priority: 1,
  },
  {
    id: 'restaurant-takeout',
    category: 'restaurant',
    frenchVariants: ["à emporter s’il vous plaît"],
    americanEnglishText: 'To go, please.',
    frenchMeaning: 'À emporter, s’il vous plaît.',
    keywords: ["emporter", "il", "plaît", "plaît.", "restaurant", "s", "vous", "à"],
    priority: 1,
  },
  {
    id: 'restaurant-reservation',
    category: 'restaurant',
    frenchVariants: ["j’ai une réservation au nom de"],
    americanEnglishText: 'I have a reservation under the name.',
    frenchMeaning: 'J’ai une réservation à ce nom.',
    keywords: ["ai", "au", "ce", "de", "j", "nom", "nom.", "restaurant", "réservation", "une"],
    priority: 1,
  },
  {
    id: 'restaurant-allergy',
    category: 'restaurant',
    frenchVariants: ["je suis allergique aux arachides"],
    americanEnglishText: 'I’m allergic to peanuts.',
    frenchMeaning: 'Je suis allergique aux arachides.',
    keywords: ["allergique", "arachides", "arachides.", "aux", "je", "restaurant", "suis"],
    priority: 1,
  },
  {
    id: 'restaurant-vegetarian',
    category: 'restaurant',
    frenchVariants: ["je suis végétarien"],
    americanEnglishText: 'I’m vegetarian.',
    frenchMeaning: 'Je suis végétarien.',
    keywords: ["je", "restaurant", "suis", "végétarien", "végétarien."],
    priority: 1,
  },
  {
    id: 'restaurant-no-spicy',
    category: 'restaurant',
    frenchVariants: ["pas trop épicé s’il vous plaît"],
    americanEnglishText: 'Not too spicy, please.',
    frenchMeaning: 'Pas trop épicé.',
    keywords: ["il", "pas", "plaît", "restaurant", "s", "trop", "vous", "épicé", "épicé."],
    priority: 1,
  },
  {
    id: 'restaurant-recommend',
    category: 'restaurant',
    frenchVariants: ["qu’est-ce que vous recommandez"],
    americanEnglishText: 'What do you recommend?',
    frenchMeaning: 'Qu’est-ce que vous recommandez ?',
    keywords: ["est-ce", "qu", "que", "recommandez", "restaurant", "vous"],
    priority: 1,
  },
  {
    id: 'restaurant-same',
    category: 'restaurant',
    frenchVariants: ["je vais prendre la même chose"],
    americanEnglishText: 'I’ll have the same thing.',
    frenchMeaning: 'Je vais prendre la même chose.',
    keywords: ["chose", "chose.", "je", "la", "même", "prendre", "restaurant", "vais"],
    priority: 1,
  },
  {
    id: 'restaurant-separate-checks',
    category: 'restaurant',
    frenchVariants: ["on peut payer séparément"],
    americanEnglishText: 'Can we pay separately?',
    frenchMeaning: 'On peut payer séparément ?',
    keywords: ["on", "payer", "peut", "restaurant", "séparément"],
    priority: 1,
  },
  {
    id: 'restaurant-box',
    category: 'restaurant',
    frenchVariants: ["puis-je avoir une boîte pour emporter"],
    americanEnglishText: 'Can I get a box to go, please?',
    frenchMeaning: 'Puis-je avoir une boîte pour emporter ?',
    keywords: ["avoir", "boîte", "emporter", "pour", "puis-je", "restaurant", "une"],
    priority: 1,
  },
  {
    id: 'hotel-reservation',
    category: 'hotel',
    frenchVariants: ["j’ai une réservation"],
    americanEnglishText: 'I have a reservation.',
    frenchMeaning: 'J’ai une réservation.',
    keywords: ["ai", "hotel", "j", "réservation", "réservation.", "une"],
    priority: 1,
  },
  {
    id: 'hotel-check-in',
    category: 'hotel',
    frenchVariants: ["je voudrais faire le check-in", "je voudrais m’enregistrer"],
    americanEnglishText: 'I’d like to check in.',
    frenchMeaning: 'Je voudrais faire le check-in.',
    keywords: ["check-in", "check-in.", "enregistrer", "faire", "hotel", "je", "le", "m", "voudrais"],
    priority: 1,
  },
  {
    id: 'hotel-check-out',
    category: 'hotel',
    frenchVariants: ["je voudrais faire le check-out"],
    americanEnglishText: 'I’d like to check out.',
    frenchMeaning: 'Je voudrais faire le check-out.',
    keywords: ["check-out", "check-out.", "faire", "hotel", "je", "le", "voudrais"],
    priority: 1,
  },
  {
    id: 'hotel-key-card',
    category: 'hotel',
    frenchVariants: ["ma carte de chambre ne fonctionne pas"],
    americanEnglishText: 'My key card isn’t working.',
    frenchMeaning: 'Ma carte de chambre ne fonctionne pas.',
    keywords: ["carte", "chambre", "de", "fonctionne", "hotel", "ma", "ne", "pas", "pas."],
    priority: 1,
  },
  {
    id: 'hotel-bags',
    category: 'hotel',
    frenchVariants: ["pouvez-vous garder mes bagages"],
    americanEnglishText: 'Can you hold my bags, please?',
    frenchMeaning: 'Pouvez-vous garder mes bagages ?',
    keywords: ["bagages", "garder", "hotel", "mes", "pouvez-vous"],
    priority: 1,
  },
  {
    id: 'hotel-room',
    category: 'hotel',
    frenchVariants: ["je voudrais une chambre"],
    americanEnglishText: 'I’d like a room.',
    frenchMeaning: 'Je voudrais une chambre.',
    keywords: ["chambre", "chambre.", "hotel", "je", "une", "voudrais"],
    priority: 1,
  },
  {
    id: 'hotel-wifi',
    category: 'hotel',
    frenchVariants: ["quel est le mot de passe du wifi"],
    americanEnglishText: 'What’s the Wi-Fi password?',
    frenchMeaning: 'Quel est le mot de passe du Wi-Fi ?',
    keywords: ["de", "du", "est", "hotel", "le", "mot", "passe", "quel", "wi-fi", "wifi"],
    priority: 1,
  },
  {
    id: 'hotel-breakfast',
    category: 'hotel',
    frenchVariants: ["à quelle heure est le petit déjeuner"],
    americanEnglishText: 'What time is breakfast?',
    frenchMeaning: 'À quelle heure est le petit déjeuner ?',
    keywords: ["déjeuner", "est", "heure", "hotel", "le", "petit", "quelle", "à"],
    priority: 1,
  },
  {
    id: 'hotel-late-checkout',
    category: 'hotel',
    frenchVariants: ["puis-je avoir un départ tardif"],
    americanEnglishText: 'Can I get a late check-out?',
    frenchMeaning: 'Puis-je avoir un départ tardif ?',
    keywords: ["avoir", "départ", "hotel", "puis-je", "tardif", "un"],
    priority: 1,
  },
  {
    id: 'hotel-towels',
    category: 'hotel',
    frenchVariants: ["pouvez-vous envoyer des serviettes"],
    americanEnglishText: 'Can you send up some towels, please?',
    frenchMeaning: 'Pouvez-vous envoyer des serviettes ?',
    keywords: ["des", "envoyer", "hotel", "pouvez-vous", "serviettes"],
    priority: 1,
  },
  {
    id: 'hotel-noisy',
    category: 'hotel',
    frenchVariants: ["la chambre est bruyante"],
    americanEnglishText: 'The room is noisy.',
    frenchMeaning: 'La chambre est bruyante.',
    keywords: ["bruyante", "bruyante.", "chambre", "est", "hotel", "la"],
    priority: 1,
  },
  {
    id: 'hotel-ac',
    category: 'hotel',
    frenchVariants: ["la climatisation ne marche pas"],
    americanEnglishText: 'The air conditioning isn’t working.',
    frenchMeaning: 'La climatisation ne marche pas.',
    keywords: ["climatisation", "hotel", "la", "marche", "ne", "pas", "pas."],
    priority: 1,
  },
  {
    id: 'hotel-shuttle',
    category: 'hotel',
    frenchVariants: ["y a-t-il une navette pour l’aéroport"],
    americanEnglishText: 'Is there an airport shuttle?',
    frenchMeaning: 'Y a-t-il une navette pour l’aéroport ?',
    keywords: ["a-t-il", "aéroport", "hotel", "l", "navette", "pour", "une", "y"],
    priority: 1,
  },
  {
    id: 'hotel-deposit',
    category: 'hotel',
    frenchVariants: ["combien coûte la caution"],
    americanEnglishText: 'How much is the deposit?',
    frenchMeaning: 'Combien coûte la caution ?',
    keywords: ["caution", "combien", "coûte", "hotel", "la"],
    priority: 1,
  },
  {
    id: 'hotel-invoice',
    category: 'hotel',
    frenchVariants: ["puis-je avoir une facture"],
    americanEnglishText: 'Can I get an invoice, please?',
    frenchMeaning: 'Puis-je avoir une facture ?',
    keywords: ["avoir", "facture", "hotel", "puis-je", "une"],
    priority: 1,
  },
  {
    id: 'hotel-safe',
    category: 'hotel',
    frenchVariants: ["le coffre-fort ne s’ouvre pas"],
    americanEnglishText: 'The safe won’t open.',
    frenchMeaning: 'Le coffre-fort ne s’ouvre pas.',
    keywords: ["coffre-fort", "hotel", "le", "ne", "ouvre", "pas", "pas.", "s"],
    priority: 1,
  },
  {
    id: 'hotel-housekeeping',
    category: 'hotel',
    frenchVariants: ["pouvez-vous nettoyer la chambre"],
    americanEnglishText: 'Can you clean the room, please?',
    frenchMeaning: 'Pouvez-vous nettoyer la chambre ?',
    keywords: ["chambre", "hotel", "la", "nettoyer", "pouvez-vous"],
    priority: 1,
  },
  {
    id: 'car-pickup',
    category: 'car',
    frenchVariants: ["je dois récupérer ma voiture de location"],
    americanEnglishText: 'I need to pick up my rental car.',
    frenchMeaning: 'Je dois récupérer ma voiture de location.',
    keywords: ["car", "de", "dois", "je", "location", "location.", "ma", "récupérer", "voiture"],
    priority: 1,
  },
  {
    id: 'car-license',
    category: 'car',
    frenchVariants: ["voici mon permis de conduire"],
    americanEnglishText: 'Here’s my driver’s license.',
    frenchMeaning: 'Voici mon permis de conduire.',
    keywords: ["car", "conduire", "conduire.", "de", "mon", "permis", "voici"],
    priority: 1,
  },
  {
    id: 'car-parking',
    category: 'car',
    frenchVariants: ["où est le parking"],
    americanEnglishText: 'Where’s the parking lot?',
    frenchMeaning: 'Où est le parking ?',
    keywords: ["car", "est", "le", "où", "parking"],
    priority: 1,
  },
  {
    id: 'car-return',
    category: 'car',
    frenchVariants: ["je voudrais rendre la voiture"],
    americanEnglishText: 'I’d like to return the car.',
    frenchMeaning: 'Je voudrais rendre la voiture.',
    keywords: ["car", "je", "la", "rendre", "voiture", "voiture.", "voudrais"],
    priority: 1,
  },
  {
    id: 'car-insurance',
    category: 'car',
    frenchVariants: ["est-ce que l’assurance est incluse"],
    americanEnglishText: 'Is insurance included?',
    frenchMeaning: 'Est-ce que l’assurance est incluse ?',
    keywords: ["assurance", "car", "est", "est-ce", "incluse", "l", "que"],
    priority: 1,
  },
  {
    id: 'car-gas',
    category: 'car',
    frenchVariants: ["où puis-je trouver de l’essence"],
    americanEnglishText: 'Where can I get gas?',
    frenchMeaning: 'Où puis-je trouver de l’essence ?',
    keywords: ["car", "de", "essence", "l", "où", "puis-je", "trouver"],
    priority: 1,
  },
  {
    id: 'car-flat',
    category: 'car',
    frenchVariants: ["j’ai un pneu crevé"],
    americanEnglishText: 'I have a flat tire.',
    frenchMeaning: 'J’ai un pneu crevé.',
    keywords: ["ai", "car", "crevé", "crevé.", "j", "pneu", "un"],
    priority: 1,
  },
  {
    id: 'car-accident',
    category: 'car',
    frenchVariants: ["j’ai eu un accident"],
    americanEnglishText: 'I had an accident.',
    frenchMeaning: 'J’ai eu un accident.',
    keywords: ["accident", "accident.", "ai", "car", "eu", "j", "un"],
    priority: 1,
  },
  {
    id: 'car-gps',
    category: 'car',
    frenchVariants: ["le gps ne fonctionne pas"],
    americanEnglishText: 'The GPS isn’t working.',
    frenchMeaning: 'Le GPS ne fonctionne pas.',
    keywords: ["car", "fonctionne", "gps", "le", "ne", "pas", "pas."],
    priority: 1,
  },
  {
    id: 'car-toll',
    category: 'car',
    frenchVariants: ["comment payer le péage"],
    americanEnglishText: 'How do I pay the toll?',
    frenchMeaning: 'Comment payer le péage ?',
    keywords: ["car", "comment", "le", "payer", "péage"],
    priority: 1,
  },
  {
    id: 'car-full-tank',
    category: 'car',
    frenchVariants: ["dois-je rendre la voiture avec le plein"],
    americanEnglishText: 'Do I need to return the car with a full tank?',
    frenchMeaning: 'Dois-je rendre la voiture avec le plein ?',
    keywords: ["avec", "car", "dois-je", "la", "le", "plein", "rendre", "voiture"],
    priority: 1,
  },
  {
    id: 'car-damage',
    category: 'car',
    frenchVariants: ["il y a une rayure sur la voiture"],
    americanEnglishText: 'There’s a scratch on the car.',
    frenchMeaning: 'Il y a une rayure sur la voiture.',
    keywords: ["a", "car", "il", "la", "rayure", "sur", "une", "voiture", "voiture.", "y"],
    priority: 1,
  },
  {
    id: 'car-extend',
    category: 'car',
    frenchVariants: ["je voudrais prolonger la location"],
    americanEnglishText: 'I’d like to extend the rental.',
    frenchMeaning: 'Je voudrais prolonger la location.',
    keywords: ["car", "je", "la", "location", "location.", "prolonger", "voudrais"],
    priority: 1,
  },
  {
    id: 'car-dropoff',
    category: 'car',
    frenchVariants: ["où dois-je déposer la voiture"],
    americanEnglishText: 'Where should I drop off the car?',
    frenchMeaning: 'Où dois-je déposer la voiture ?',
    keywords: ["car", "dois-je", "déposer", "la", "où", "voiture"],
    priority: 1,
  },
  {
    id: 'car-keys',
    category: 'car',
    frenchVariants: ["j’ai perdu les clés"],
    americanEnglishText: 'I lost the keys.',
    frenchMeaning: 'J’ai perdu les clés.',
    keywords: ["ai", "car", "clés", "clés.", "j", "les", "perdu"],
    priority: 1,
  },
  {
    id: 'car-battery',
    category: 'car',
    frenchVariants: ["la batterie est à plat"],
    americanEnglishText: 'The battery is dead.',
    frenchMeaning: 'La batterie est à plat.',
    keywords: ["batterie", "car", "est", "la", "plat", "plat.", "à"],
    priority: 1,
  },
  {
    id: 'car-roadside',
    category: 'car',
    frenchVariants: ["j’ai besoin d’assistance routière"],
    americanEnglishText: 'I need roadside assistance.',
    frenchMeaning: 'J’ai besoin d’assistance routière.',
    keywords: ["ai", "assistance", "besoin", "car", "d", "j", "routière", "routière."],
    priority: 1,
  },
  {
    id: 'store-cost',
    category: 'store',
    frenchVariants: ["combien ça coûte"],
    americanEnglishText: 'How much is it?',
    frenchMeaning: 'Combien ça coûte ?',
    keywords: ["combien", "coûte", "store", "ça"],
    priority: 1,
  },
  {
    id: 'store-card',
    category: 'store',
    frenchVariants: ["je voudrais payer par carte"],
    americanEnglishText: 'Can I pay by card?',
    frenchMeaning: 'Je voudrais payer par carte.',
    keywords: ["carte", "carte.", "je", "par", "payer", "store", "voudrais"],
    priority: 1,
  },
  {
    id: 'store-receipt',
    category: 'store',
    frenchVariants: ["puis-je avoir un reçu"],
    americanEnglishText: 'Can I get a receipt, please?',
    frenchMeaning: 'Puis-je avoir un reçu ?',
    keywords: ["avoir", "puis-je", "reçu", "store", "un"],
    priority: 1,
  },
  {
    id: 'store-size',
    category: 'store',
    frenchVariants: ["avez-vous une autre taille"],
    americanEnglishText: 'Do you have another size?',
    frenchMeaning: 'Avez-vous une autre taille ?',
    keywords: ["autre", "avez-vous", "store", "taille", "une"],
    priority: 1,
  },
  {
    id: 'store-return',
    category: 'store',
    frenchVariants: ["puis-je retourner cet article"],
    americanEnglishText: 'Can I return this item?',
    frenchMeaning: 'Puis-je retourner cet article ?',
    keywords: ["article", "cet", "puis-je", "retourner", "store"],
    priority: 1,
  },
  {
    id: 'store-try',
    category: 'store',
    frenchVariants: ["puis-je l’essayer"],
    americanEnglishText: 'Can I try it on?',
    frenchMeaning: 'Puis-je l’essayer ?',
    keywords: ["essayer", "l", "puis-je", "store"],
    priority: 1,
  },
  {
    id: 'store-fitting',
    category: 'store',
    frenchVariants: ["où sont les cabines d’essayage"],
    americanEnglishText: 'Where are the fitting rooms?',
    frenchMeaning: 'Où sont les cabines d’essayage ?',
    keywords: ["cabines", "d", "essayage", "les", "où", "sont", "store"],
    priority: 1,
  },
  {
    id: 'store-larger',
    category: 'store',
    frenchVariants: ["avez-vous une taille plus grande"],
    americanEnglishText: 'Do you have a larger size?',
    frenchMeaning: 'Avez-vous une taille plus grande ?',
    keywords: ["avez-vous", "grande", "plus", "store", "taille", "une"],
    priority: 1,
  },
  {
    id: 'store-smaller',
    category: 'store',
    frenchVariants: ["avez-vous une taille plus petite"],
    americanEnglishText: 'Do you have a smaller size?',
    frenchMeaning: 'Avez-vous une taille plus petite ?',
    keywords: ["avez-vous", "petite", "plus", "store", "taille", "une"],
    priority: 1,
  },
  {
    id: 'store-color',
    category: 'store',
    frenchVariants: ["avez-vous une autre couleur"],
    americanEnglishText: 'Do you have another color?',
    frenchMeaning: 'Avez-vous une autre couleur ?',
    keywords: ["autre", "avez-vous", "couleur", "store", "une"],
    priority: 1,
  },
  {
    id: 'store-sale',
    category: 'store',
    frenchVariants: ["est-ce en promotion"],
    americanEnglishText: 'Is it on sale?',
    frenchMeaning: 'Est-ce en promotion ?',
    keywords: ["en", "est-ce", "promotion", "store"],
    priority: 1,
  },
  {
    id: 'store-bag',
    category: 'store',
    frenchVariants: ["puis-je avoir un sac"],
    americanEnglishText: 'Can I get a bag, please?',
    frenchMeaning: 'Puis-je avoir un sac ?',
    keywords: ["avoir", "puis-je", "sac", "store", "un"],
    priority: 1,
  },
  {
    id: 'store-cashier',
    category: 'store',
    frenchVariants: ["où est la caisse"],
    americanEnglishText: 'Where’s the checkout?',
    frenchMeaning: 'Où est la caisse ?',
    keywords: ["caisse", "est", "la", "où", "store"],
    priority: 1,
  },
  {
    id: 'store-tax',
    category: 'store',
    frenchVariants: ["la taxe est-elle incluse"],
    americanEnglishText: 'Is tax included?',
    frenchMeaning: 'La taxe est-elle incluse ?',
    keywords: ["est-elle", "incluse", "la", "store", "taxe"],
    priority: 1,
  },
  {
    id: 'store-gift',
    category: 'store',
    frenchVariants: ["c’est un cadeau"],
    americanEnglishText: 'It’s a gift.',
    frenchMeaning: 'C’est un cadeau.',
    keywords: ["c", "cadeau", "cadeau.", "est", "store", "un"],
    priority: 1,
  },
  {
    id: 'store-warranty',
    category: 'store',
    frenchVariants: ["y a-t-il une garantie"],
    americanEnglishText: 'Is there a warranty?',
    frenchMeaning: 'Y a-t-il une garantie ?',
    keywords: ["a-t-il", "garantie", "store", "une", "y"],
    priority: 1,
  },
  {
    id: 'store-open',
    category: 'store',
    frenchVariants: ["à quelle heure fermez-vous"],
    americanEnglishText: 'What time do you close?',
    frenchMeaning: 'À quelle heure fermez-vous ?',
    keywords: ["fermez-vous", "heure", "quelle", "store", "à"],
    priority: 1,
  },
  {
    id: 'border-tourist',
    category: 'border',
    frenchVariants: ["je suis touriste"],
    americanEnglishText: 'I’m a tourist.',
    frenchMeaning: 'Je suis touriste.',
    keywords: ["border", "je", "suis", "touriste", "touriste."],
    priority: 1,
  },
  {
    id: 'border-passport',
    category: 'border',
    frenchVariants: ["voici mon passeport"],
    americanEnglishText: 'Here’s my passport.',
    frenchMeaning: 'Voici mon passeport.',
    keywords: ["border", "mon", "passeport", "passeport.", "voici"],
    priority: 1,
  },
  {
    id: 'border-license',
    category: 'border',
    frenchVariants: ["voici mon permis de conduire"],
    americanEnglishText: 'Here’s my driver’s license.',
    frenchMeaning: 'Voici mon permis de conduire.',
    keywords: ["border", "conduire", "conduire.", "de", "mon", "permis", "voici"],
    priority: 1,
  },
  {
    id: 'border-poor-english',
    category: 'border',
    frenchVariants: ["je ne comprends pas bien l’anglais"],
    americanEnglishText: 'I don’t understand English very well.',
    frenchMeaning: 'Je ne comprends pas bien l’anglais.',
    keywords: ["anglais", "anglais.", "bien", "border", "comprends", "je", "l", "ne", "pas"],
    priority: 1,
  },
  {
    id: 'border-slow',
    category: 'border',
    frenchVariants: ["pouvez-vous parler plus lentement"],
    americanEnglishText: 'Could you speak more slowly, please?',
    frenchMeaning: 'Pouvez-vous parler plus lentement ?',
    keywords: ["border", "lentement", "parler", "plus", "pouvez-vous"],
    priority: 1,
  },
  {
    id: 'border-vacation',
    category: 'border',
    frenchVariants: ["je viens pour les vacances"],
    americanEnglishText: 'I’m here on vacation.',
    frenchMeaning: 'Je viens pour les vacances.',
    keywords: ["border", "je", "les", "pour", "vacances", "vacances.", "viens"],
    priority: 1,
  },
  {
    id: 'border-business',
    category: 'border',
    frenchVariants: ["je viens pour le travail"],
    americanEnglishText: 'I’m here for work.',
    frenchMeaning: 'Je viens pour le travail.',
    keywords: ["border", "je", "le", "pour", "travail", "travail.", "viens"],
    priority: 1,
  },
  {
    id: 'border-stay',
    category: 'border',
    frenchVariants: ["je reste deux semaines"],
    americanEnglishText: 'I’m staying for two weeks.',
    frenchMeaning: 'Je reste deux semaines.',
    keywords: ["border", "deux", "je", "reste", "semaines", "semaines."],
    priority: 1,
  },
  {
    id: 'border-hotel-address',
    category: 'border',
    frenchVariants: ["voici l’adresse de mon hôtel"],
    americanEnglishText: 'Here’s my hotel address.',
    frenchMeaning: 'Voici l’adresse de mon hôtel.',
    keywords: ["adresse", "border", "de", "hôtel", "hôtel.", "l", "mon", "voici"],
    priority: 1,
  },
  {
    id: 'border-return-ticket',
    category: 'border',
    frenchVariants: ["voici mon billet retour"],
    americanEnglishText: 'Here’s my return ticket.',
    frenchMeaning: 'Voici mon billet retour.',
    keywords: ["billet", "border", "mon", "retour", "retour.", "voici"],
    priority: 1,
  },
  {
    id: 'border-nothing-declare',
    category: 'border',
    frenchVariants: ["je n’ai rien à déclarer"],
    americanEnglishText: 'I have nothing to declare.',
    frenchMeaning: 'Je n’ai rien à déclarer.',
    keywords: ["ai", "border", "déclarer", "déclarer.", "je", "n", "rien", "à"],
    priority: 1,
  },
  {
    id: 'border-visa',
    category: 'border',
    frenchVariants: ["voici mon visa"],
    americanEnglishText: 'Here’s my visa.',
    frenchMeaning: 'Voici mon visa.',
    keywords: ["border", "mon", "visa", "visa.", "voici"],
    priority: 1,
  },
  {
    id: 'border-purpose',
    category: 'border',
    frenchVariants: ["le but de mon voyage est le tourisme"],
    americanEnglishText: 'The purpose of my trip is tourism.',
    frenchMeaning: 'Le but de mon voyage est le tourisme.',
    keywords: ["border", "but", "de", "est", "le", "mon", "tourisme", "tourisme.", "voyage"],
    priority: 1,
  },
  {
    id: 'border-translator',
    category: 'border',
    frenchVariants: ["puis-je utiliser mon traducteur"],
    americanEnglishText: 'Can I use my translator?',
    frenchMeaning: 'Puis-je utiliser mon traducteur ?',
    keywords: ["border", "mon", "puis-je", "traducteur", "utiliser"],
    priority: 1,
  },
  {
    id: 'border-question-repeat',
    category: 'border',
    frenchVariants: ["pouvez-vous répéter la question"],
    americanEnglishText: 'Could you repeat the question, please?',
    frenchMeaning: 'Pouvez-vous répéter la question ?',
    keywords: ["border", "la", "pouvez-vous", "question", "répéter"],
    priority: 1,
  },
  {
    id: 'border-rental-car',
    category: 'border',
    frenchVariants: ["j’ai une voiture de location"],
    americanEnglishText: 'I have a rental car.',
    frenchMeaning: 'J’ai une voiture de location.',
    keywords: ["ai", "border", "de", "j", "location", "location.", "une", "voiture"],
    priority: 1,
  },
  {
    id: 'border-address-us',
    category: 'border',
    frenchVariants: ["je n’ai pas d’adresse aux États-Unis"],
    americanEnglishText: 'I don’t have a U.S. address.',
    frenchMeaning: 'Je n’ai pas d’adresse aux États-Unis.',
    keywords: ["adresse", "ai", "aux", "border", "d", "je", "n", "pas", "états-unis", "états-unis."],
    priority: 1,
  },
  {
    id: 'emergency-help',
    category: 'emergency',
    frenchVariants: ["j’ai besoin d’aide"],
    americanEnglishText: 'I need help.',
    frenchMeaning: 'J’ai besoin d’aide.',
    keywords: ["ai", "aide", "aide.", "besoin", "d", "emergency", "j"],
    priority: 1,
  },
  {
    id: 'emergency-ambulance',
    category: 'emergency',
    frenchVariants: ["appelez une ambulance"],
    americanEnglishText: 'Please call an ambulance.',
    frenchMeaning: 'Appelez une ambulance.',
    keywords: ["ambulance", "ambulance.", "appelez", "emergency", "une"],
    priority: 1,
  },
  {
    id: 'emergency-hurt',
    category: 'emergency',
    frenchVariants: ["je suis blessé"],
    americanEnglishText: 'I’m hurt.',
    frenchMeaning: 'Je suis blessé.',
    keywords: ["blessé", "blessé.", "emergency", "je", "suis"],
    priority: 1,
  },
  {
    id: 'emergency-sick',
    category: 'emergency',
    frenchVariants: ["je ne me sens pas bien"],
    americanEnglishText: 'I don’t feel well.',
    frenchMeaning: 'Je ne me sens pas bien.',
    keywords: ["bien", "bien.", "emergency", "je", "me", "ne", "pas", "sens"],
    priority: 1,
  },
  {
    id: 'emergency-hospital',
    category: 'emergency',
    frenchVariants: ["où est l’hôpital le plus proche"],
    americanEnglishText: 'Where’s the nearest hospital?',
    frenchMeaning: 'Où est l’hôpital le plus proche ?',
    keywords: ["emergency", "est", "hôpital", "l", "le", "où", "plus", "proche"],
    priority: 1,
  },
  {
    id: 'emergency-doctor',
    category: 'emergency',
    frenchVariants: ["j’ai besoin d’un médecin"],
    americanEnglishText: 'I need a doctor.',
    frenchMeaning: 'J’ai besoin d’un médecin.',
    keywords: ["ai", "besoin", "d", "emergency", "j", "médecin", "médecin.", "un"],
    priority: 1,
  },
  {
    id: 'emergency-allergy',
    category: 'emergency',
    frenchVariants: ["j’ai une allergie grave"],
    americanEnglishText: 'I have a severe allergy.',
    frenchMeaning: 'J’ai une allergie grave.',
    keywords: ["ai", "allergie", "emergency", "grave", "grave.", "j", "une"],
    priority: 1,
  },
  {
    id: 'emergency-meds',
    category: 'emergency',
    frenchVariants: ["j’ai besoin de mes médicaments"],
    americanEnglishText: 'I need my medication.',
    frenchMeaning: 'J’ai besoin de mes médicaments.',
    keywords: ["ai", "besoin", "de", "emergency", "j", "mes", "médicaments", "médicaments."],
    priority: 1,
  },
  {
    id: 'emergency-pain',
    category: 'emergency',
    frenchVariants: ["j’ai mal ici"],
    americanEnglishText: 'I have pain here.',
    frenchMeaning: 'J’ai mal ici.',
    keywords: ["ai", "emergency", "ici", "ici.", "j", "mal"],
    priority: 1,
  },
  {
    id: 'emergency-lost',
    category: 'emergency',
    frenchVariants: ["je suis perdu"],
    americanEnglishText: 'I’m lost.',
    frenchMeaning: 'Je suis perdu.',
    keywords: ["emergency", "je", "perdu", "perdu.", "suis"],
    priority: 1,
  },
  {
    id: 'emergency-stolen',
    category: 'emergency',
    frenchVariants: ["on m’a volé mon téléphone"],
    americanEnglishText: 'My phone was stolen.',
    frenchMeaning: 'On m’a volé mon téléphone.',
    keywords: ["a", "emergency", "m", "mon", "on", "téléphone", "téléphone.", "volé"],
    priority: 1,
  },
  {
    id: 'emergency-police',
    category: 'emergency',
    frenchVariants: ["appelez la police"],
    americanEnglishText: 'Please call the police.',
    frenchMeaning: 'Appelez la police.',
    keywords: ["appelez", "emergency", "la", "police", "police."],
    priority: 1,
  },
  {
    id: 'emergency-fire',
    category: 'emergency',
    frenchVariants: ["il y a un incendie"],
    americanEnglishText: 'There’s a fire.',
    frenchMeaning: 'Il y a un incendie.',
    keywords: ["a", "emergency", "il", "incendie", "incendie.", "un", "y"],
    priority: 1,
  },
  {
    id: 'emergency-address',
    category: 'emergency',
    frenchVariants: ["quelle est l’adresse ici"],
    americanEnglishText: 'What’s the address here?',
    frenchMeaning: 'Quelle est l’adresse ici ?',
    keywords: ["adresse", "emergency", "est", "ici", "l", "quelle"],
    priority: 1,
  },
  {
    id: 'emergency-diabetic',
    category: 'emergency',
    frenchVariants: ["je suis diabétique"],
    americanEnglishText: 'I’m diabetic.',
    frenchMeaning: 'Je suis diabétique.',
    keywords: ["diabétique", "diabétique.", "emergency", "je", "suis"],
    priority: 1,
  },
  {
    id: 'emergency-breathe',
    category: 'emergency',
    frenchVariants: ["j’ai du mal à respirer"],
    americanEnglishText: 'I’m having trouble breathing.',
    frenchMeaning: 'J’ai du mal à respirer.',
    keywords: ["ai", "du", "emergency", "j", "mal", "respirer", "respirer.", "à"],
    priority: 1,
  },
  {
    id: 'emergency-emergency-contact',
    category: 'emergency',
    frenchVariants: ["voici mon contact d’urgence"],
    americanEnglishText: 'Here’s my emergency contact.',
    frenchMeaning: 'Voici mon contact d’urgence.',
    keywords: ["contact", "d", "emergency", "mon", "urgence", "urgence.", "voici"],
    priority: 1,
  },
  {
    id: 'direction-exit',
    category: 'direction',
    frenchVariants: ["je cherche la sortie"],
    americanEnglishText: 'I’m looking for the exit.',
    frenchMeaning: 'Je cherche la sortie.',
    keywords: ["cherche", "direction", "je", "la", "sortie", "sortie."],
    priority: 1,
  },
  {
    id: 'direction-entrance',
    category: 'direction',
    frenchVariants: ["où est l’entrée"],
    americanEnglishText: 'Where’s the entrance?',
    frenchMeaning: 'Où est l’entrée ?',
    keywords: ["direction", "entrée", "est", "l", "où"],
    priority: 1,
  },
  {
    id: 'direction-far',
    category: 'direction',
    frenchVariants: ["c’est loin d’ici"],
    americanEnglishText: 'Is it far from here?',
    frenchMeaning: 'C’est loin d’ici ?',
    keywords: ["c", "d", "direction", "est", "ici", "loin"],
    priority: 1,
  },
  {
    id: 'direction-lost',
    category: 'direction',
    frenchVariants: ["je suis perdu"],
    americanEnglishText: 'I’m lost.',
    frenchMeaning: 'Je suis perdu.',
    keywords: ["direction", "je", "perdu", "perdu.", "suis"],
    priority: 1,
  },
  {
    id: 'direction-map',
    category: 'direction',
    frenchVariants: ["pouvez-vous me montrer sur la carte"],
    americanEnglishText: 'Can you show me on the map?',
    frenchMeaning: 'Pouvez-vous me montrer sur la carte ?',
    keywords: ["carte", "direction", "la", "me", "montrer", "pouvez-vous", "sur"],
    priority: 1,
  },
  {
    id: 'direction-airport',
    category: 'direction',
    frenchVariants: ["comment aller à l’aéroport"],
    americanEnglishText: 'How do I get to the airport?',
    frenchMeaning: 'Comment aller à l’aéroport ?',
    keywords: ["aller", "aéroport", "comment", "direction", "l", "à"],
    priority: 1,
  },
  {
    id: 'direction-subway',
    category: 'direction',
    frenchVariants: ["où est le métro"],
    americanEnglishText: 'Where’s the subway?',
    frenchMeaning: 'Où est le métro ?',
    keywords: ["direction", "est", "le", "métro", "où"],
    priority: 1,
  },
  {
    id: 'direction-bus',
    category: 'direction',
    frenchVariants: ["où est l’arrêt de bus"],
    americanEnglishText: 'Where’s the bus stop?',
    frenchMeaning: 'Où est l’arrêt de bus ?',
    keywords: ["arrêt", "bus", "de", "direction", "est", "l", "où"],
    priority: 1,
  },
  {
    id: 'direction-train',
    category: 'direction',
    frenchVariants: ["où est la gare"],
    americanEnglishText: 'Where’s the train station?',
    frenchMeaning: 'Où est la gare ?',
    keywords: ["direction", "est", "gare", "la", "où"],
    priority: 1,
  },
  {
    id: 'direction-left',
    category: 'direction',
    frenchVariants: ["dois-je tourner à gauche"],
    americanEnglishText: 'Should I turn left?',
    frenchMeaning: 'Dois-je tourner à gauche ?',
    keywords: ["direction", "dois-je", "gauche", "tourner", "à"],
    priority: 1,
  },
  {
    id: 'direction-right',
    category: 'direction',
    frenchVariants: ["dois-je tourner à droite"],
    americanEnglishText: 'Should I turn right?',
    frenchMeaning: 'Dois-je tourner à droite ?',
    keywords: ["direction", "dois-je", "droite", "tourner", "à"],
    priority: 1,
  },
  {
    id: 'direction-straight',
    category: 'direction',
    frenchVariants: ["dois-je aller tout droit"],
    americanEnglishText: 'Should I go straight?',
    frenchMeaning: 'Dois-je aller tout droit ?',
    keywords: ["aller", "direction", "dois-je", "droit", "tout"],
    priority: 1,
  },
  {
    id: 'direction-address',
    category: 'direction',
    frenchVariants: ["je cherche cette adresse"],
    americanEnglishText: 'I’m looking for this address.',
    frenchMeaning: 'Je cherche cette adresse.',
    keywords: ["adresse", "adresse.", "cette", "cherche", "direction", "je"],
    priority: 1,
  },
  {
    id: 'direction-walk',
    category: 'direction',
    frenchVariants: ["est-ce que je peux y aller à pied"],
    americanEnglishText: 'Can I walk there?',
    frenchMeaning: 'Est-ce que je peux y aller à pied ?',
    keywords: ["aller", "direction", "est-ce", "je", "peux", "pied", "que", "y", "à"],
    priority: 1,
  },
  {
    id: 'direction-taxi',
    category: 'direction',
    frenchVariants: ["où puis-je prendre un taxi"],
    americanEnglishText: 'Where can I get a taxi?',
    frenchMeaning: 'Où puis-je prendre un taxi ?',
    keywords: ["direction", "où", "prendre", "puis-je", "taxi", "un"],
    priority: 1,
  },
  {
    id: 'direction-rideshare',
    category: 'direction',
    frenchVariants: ["où est la zone uber"],
    americanEnglishText: 'Where’s the rideshare pickup area?',
    frenchMeaning: 'Où est la zone Uber ?',
    keywords: ["direction", "est", "la", "où", "uber", "zone"],
    priority: 1,
  },
  {
    id: 'direction-floor',
    category: 'direction',
    frenchVariants: ["à quel étage est-ce"],
    americanEnglishText: 'What floor is it on?',
    frenchMeaning: 'À quel étage est-ce ?',
    keywords: ["direction", "est-ce", "quel", "à", "étage"],
    priority: 1,
  },
  {
    id: 'payment-card',
    category: 'payment',
    frenchVariants: ["je voudrais payer par carte"],
    americanEnglishText: 'Can I pay by card?',
    frenchMeaning: 'Je voudrais payer par carte.',
    keywords: ["carte", "carte.", "je", "par", "payer", "payment", "voudrais"],
    priority: 1,
  },
  {
    id: 'payment-cash',
    category: 'payment',
    frenchVariants: ["je voudrais payer en espèces"],
    americanEnglishText: 'Can I pay in cash?',
    frenchMeaning: 'Je voudrais payer en espèces.',
    keywords: ["en", "espèces", "espèces.", "je", "payer", "payment", "voudrais"],
    priority: 1,
  },
  {
    id: 'payment-declined',
    category: 'payment',
    frenchVariants: ["le paiement a été refusé"],
    americanEnglishText: 'The payment was declined.',
    frenchMeaning: 'Le paiement a été refusé.',
    keywords: ["a", "le", "paiement", "payment", "refusé", "refusé.", "été"],
    priority: 1,
  },
  {
    id: 'payment-receipt',
    category: 'payment',
    frenchVariants: ["puis-je avoir un reçu"],
    americanEnglishText: 'Can I get a receipt, please?',
    frenchMeaning: 'Puis-je avoir un reçu ?',
    keywords: ["avoir", "payment", "puis-je", "reçu", "un"],
    priority: 1,
  },
  {
    id: 'payment-tip',
    category: 'payment',
    frenchVariants: ["est-ce que le pourboire est inclus"],
    americanEnglishText: 'Is the tip included?',
    frenchMeaning: 'Est-ce que le pourboire est inclus ?',
    keywords: ["est", "est-ce", "inclus", "le", "payment", "pourboire", "que"],
    priority: 1,
  },
  {
    id: 'payment-apple-pay',
    category: 'payment',
    frenchVariants: ["acceptez-vous apple pay"],
    americanEnglishText: 'Do you take Apple Pay?',
    frenchMeaning: 'Acceptez-vous Apple Pay ?',
    keywords: ["acceptez-vous", "apple", "pay", "payment"],
    priority: 1,
  },
  {
    id: 'payment-split',
    category: 'payment',
    frenchVariants: ["pouvons-nous partager la note"],
    americanEnglishText: 'Can we split the bill?',
    frenchMeaning: 'Pouvons-nous partager la note ?',
    keywords: ["la", "note", "partager", "payment", "pouvons-nous"],
    priority: 1,
  },
  {
    id: 'payment-try-again',
    category: 'payment',
    frenchVariants: ["pouvons-nous réessayer"],
    americanEnglishText: 'Can we try again?',
    frenchMeaning: 'Pouvons-nous réessayer ?',
    keywords: ["payment", "pouvons-nous", "réessayer"],
    priority: 1,
  },
  {
    id: 'payment-charged-twice',
    category: 'payment',
    frenchVariants: ["j’ai été débité deux fois"],
    americanEnglishText: 'I was charged twice.',
    frenchMeaning: 'J’ai été débité deux fois.',
    keywords: ["ai", "deux", "débité", "fois", "fois.", "j", "payment", "été"],
    priority: 1,
  },
  {
    id: 'payment-wrong-amount',
    category: 'payment',
    frenchVariants: ["le montant est incorrect"],
    americanEnglishText: 'The amount is wrong.',
    frenchMeaning: 'Le montant est incorrect.',
    keywords: ["est", "incorrect", "incorrect.", "le", "montant", "payment"],
    priority: 1,
  },
  {
    id: 'payment-pin',
    category: 'payment',
    frenchVariants: ["dois-je entrer mon code"],
    americanEnglishText: 'Do I need to enter my PIN?',
    frenchMeaning: 'Dois-je entrer mon code ?',
    keywords: ["code", "dois-je", "entrer", "mon", "payment"],
    priority: 1,
  },
  {
    id: 'payment-signature',
    category: 'payment',
    frenchVariants: ["dois-je signer"],
    americanEnglishText: 'Do I need to sign?',
    frenchMeaning: 'Dois-je signer ?',
    keywords: ["dois-je", "payment", "signer"],
    priority: 1,
  },
  {
    id: 'payment-no-cash',
    category: 'payment',
    frenchVariants: ["je n’ai pas d’espèces"],
    americanEnglishText: 'I don’t have cash.',
    frenchMeaning: 'Je n’ai pas d’espèces.',
    keywords: ["ai", "d", "espèces", "espèces.", "je", "n", "pas", "payment"],
    priority: 1,
  },
  {
    id: 'payment-atm',
    category: 'payment',
    frenchVariants: ["où est le distributeur"],
    americanEnglishText: 'Where’s the ATM?',
    frenchMeaning: 'Où est le distributeur ?',
    keywords: ["distributeur", "est", "le", "où", "payment"],
    priority: 1,
  },
  {
    id: 'payment-change',
    category: 'payment',
    frenchVariants: ["pouvez-vous me rendre la monnaie"],
    americanEnglishText: 'Can I get change, please?',
    frenchMeaning: 'Pouvez-vous me rendre la monnaie ?',
    keywords: ["la", "me", "monnaie", "payment", "pouvez-vous", "rendre"],
    priority: 1,
  },
  {
    id: 'payment-total',
    category: 'payment',
    frenchVariants: ["quel est le total"],
    americanEnglishText: 'What’s the total?',
    frenchMeaning: 'Quel est le total ?',
    keywords: ["est", "le", "payment", "quel", "total"],
    priority: 1,
  },
  {
    id: 'payment-refund',
    category: 'payment',
    frenchVariants: ["je voudrais un remboursement"],
    americanEnglishText: 'I’d like a refund.',
    frenchMeaning: 'Je voudrais un remboursement.',
    keywords: ["je", "payment", "remboursement", "remboursement.", "un", "voudrais"],
    priority: 1,
  },
];

export const offlineCategories = {
  restaurant: 'Restaurant',
  hotel: 'Hôtel',
  car: 'Voiture',
  store: 'Magasin',
  border: 'Police / Douane',
  emergency: 'Urgence',
  direction: 'Direction',
  payment: 'Paiement',
  general: 'Général',
};

const politeNoise = /\b(?:bonjour|bonsoir|salut|excusez moi|excuse moi|s il vous plait|svp|merci)\b/g;
const stopWords = new Set(['je', 'j', 'me', 'm', 'ma', 'mon', 'mes', 'le', 'la', 'les', 'un', 'une', 'de', 'du', 'des', 'ce', 'cet', 'cette', 'ça', 'ca', 'est', 'sont', 'a', 'au', 'aux', 'en', 'pour', 'par', 'avec', 'sur', 'dans', 'ici', 'il', 'y', 'vous', 'pouvez', 'puis']);

export function normalizeOfflineText(text = '') {
  return String(text)
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[’']/g, ' ')
    .replace(/[^a-z0-9]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function normalizeWithoutPoliteNoise(text = '') {
  return normalizeOfflineText(text).replace(politeNoise, ' ').replace(/\s+/g, ' ').trim();
}

function tokensFor(text = '') {
  return normalizeWithoutPoliteNoise(text).split(' ').filter((token) => token && !stopWords.has(token) && token.length > 1);
}

function phraseScore(query, phrase) {
  const normalizedQuery = normalizeOfflineText(query);
  const quietQuery = normalizeWithoutPoliteNoise(query);
  let best = 0;
  for (const variant of phrase.frenchVariants) {
    const normalizedVariant = normalizeOfflineText(variant);
    const quietVariant = normalizeWithoutPoliteNoise(variant);
    if (normalizedQuery === normalizedVariant) best = Math.max(best, 1);
    if (quietQuery === quietVariant) best = Math.max(best, 0.96);
    if (quietQuery && quietVariant && (quietQuery.includes(quietVariant) || quietVariant.includes(quietQuery))) best = Math.max(best, 0.88);
    const queryTokens = tokensFor(query);
    const variantTokens = tokensFor(variant);
    const phraseTokens = new Set([...variantTokens, ...(phrase.keywords || []).map(normalizeOfflineText)]);
    const hits = queryTokens.filter((token) => phraseTokens.has(token));
    if (queryTokens.length && hits.length) {
      const coverage = hits.length / Math.max(queryTokens.length, variantTokens.length || 1);
      best = Math.max(best, 0.42 + coverage * 0.43);
    }
  }
  return Math.min(1, best + Math.min(phrase.priority || 1, 10) / 1000);
}

export function findOfflinePhrase(text = '', options = {}) {
  const category = options.category;
  const candidates = offlinePhrases;
  const ranked = candidates
    .map((phrase) => ({ phrase, confidence: phraseScore(text, phrase) }))
    .filter((match) => match.confidence >= 0.62)
    .sort((a, b) => b.confidence - a.confidence || (b.phrase.priority || 0) - (a.phrase.priority || 0));
  return ranked[0] || null;
}
