export const offlineCategories = {
  general: 'Général',
  hotel: 'Hôtel',
  restaurant: 'Restaurant',
  car: 'Voiture',
  store: 'Magasin / paiement',
  emergency: 'Urgence',
};

export const frenchObjects = {
  'serviettes de bain': { en: 'bath towels', category: 'hotel' },
  'serviettes propres': { en: 'clean towels', category: 'hotel' },
  'serviettes supplémentaires': { en: 'extra towels', category: 'hotel' },
  'papier toilette': { en: 'toilet paper', category: 'hotel' },
  savon: { en: 'soap', category: 'hotel' },
  shampoing: { en: 'shampoo', category: 'hotel' },
  'gel douche': { en: 'body wash', category: 'hotel' },
  oreiller: { en: 'a pillow', category: 'hotel' },
  oreillers: { en: 'pillows', category: 'hotel' },
  couverture: { en: 'a blanket', category: 'hotel' },
  drap: { en: 'a sheet', category: 'hotel' },
  'clé de chambre': { en: 'my room key', category: 'hotel' },
  'carte de chambre': { en: 'my key card', category: 'hotel' },
  'sèche-cheveux': { en: 'a hair dryer', category: 'hotel' },
  'fer à repasser': { en: 'an iron', category: 'hotel' },
  adaptateur: { en: 'an adapter', category: 'hotel' },
  'bouteille d’eau': { en: 'a bottle of water', category: 'hotel' },
  addition: { en: 'the check', category: 'restaurant' },
  eau: { en: 'water', category: 'restaurant' },
  serviettes: { en: 'napkins', category: 'restaurant' },
  menu: { en: 'a menu', category: 'restaurant' },
  fourchette: { en: 'a fork', category: 'restaurant' },
  couteau: { en: 'a knife', category: 'restaurant' },
  cuillère: { en: 'a spoon', category: 'restaurant' },
  sel: { en: 'salt', category: 'restaurant' },
  poivre: { en: 'pepper', category: 'restaurant' },
  sauce: { en: 'sauce', category: 'restaurant' },
  table: { en: 'a table', category: 'restaurant' },
  toilettes: { en: 'the restroom', category: 'restaurant' },
  'voiture de location': { en: 'rental car', category: 'car' },
  'permis de conduire': { en: 'driver’s license', category: 'car' },
  assurance: { en: 'insurance', category: 'car' },
  essence: { en: 'gas', category: 'car' },
  parking: { en: 'parking lot', category: 'car' },
  clés: { en: 'keys', category: 'car' },
  reçu: { en: 'receipt', category: 'store' },
  sac: { en: 'bag', category: 'store' },
  'autre taille': { en: 'another size', category: 'store' },
  remboursement: { en: 'refund', category: 'store' },
  échange: { en: 'exchange', category: 'store' },
  prix: { en: 'price', category: 'store' },
  'carte bancaire': { en: 'card', category: 'store' },
  espèces: { en: 'cash', category: 'store' },
};

export const frenchDirectPhrases = {
  'bonjour': ['Hi.', 'Bonjour.'],
  'bonjour comment allez-vous': ['Hi, how are you doing?', 'Bonjour, comment allez-vous ?'],
  'j’espère que vous allez bien': ['I hope you’re doing well.', 'J’espère que vous allez bien.'],
  'bonjour j’espère que vous allez bien': ['Hi, I hope you’re doing well.', 'Bonjour, j’espère que vous allez bien.'],
  'j’espère que tout va bien pour vous': ['I hope you’re doing well.', 'J’espère que tout va bien pour vous.'],
  'bonjour j’espère que tout va bien pour vous': ['Hi, I hope you’re doing well.', 'Bonjour, j’espère que tout va bien pour vous.'],
  'merci': ['Thank you.', 'Merci.'],
  'merci beaucoup': ['Thank you very much.', 'Merci beaucoup.'],
  'au revoir': ['Goodbye.', 'Au revoir.'],
  'il me faudrait des serviettes de bain': ['Could I get some bath towels, please?', 'Il me faudrait des serviettes de bain.'],
  'j’aurais besoin de serviettes propres': ['Could I get some clean towels, please?', 'J’aurais besoin de serviettes propres.'],
  'il manque du papier toilette': ['We’re out of toilet paper.', 'Il manque du papier toilette.'],
  'ma carte de chambre ne fonctionne pas': ['My key card isn’t working.', 'Ma carte de chambre ne fonctionne pas.'],
  'il n’y a pas d’eau chaude': ['There’s no hot water.', 'Il n’y a pas d’eau chaude.'],
  'la climatisation ne fonctionne pas': ['The air conditioning isn’t working.', 'La climatisation ne fonctionne pas.'],
  'le chauffage ne fonctionne pas': ['The heat isn’t working.', 'Le chauffage ne fonctionne pas.'],
  'je voudrais changer de chambre': ['I’d like to change rooms.', 'Je voudrais changer de chambre.'],
  'pouvez-vous nettoyer la chambre': ['Could you clean the room, please?', 'Pouvez-vous nettoyer la chambre ?'],
  'pouvez-vous garder mes bagages': ['Could you hold my bags, please?', 'Pouvez-vous garder mes bagages ?'],
  'je voudrais payer l’addition': ['Can I get the check, please?', 'Je voudrais payer l’addition.'],
  'l’addition s’il vous plaît': ['Can I get the check, please?', 'L’addition, s’il vous plaît.'],
  'je voudrais de l’eau': ['Could I get some water, please?', 'Je voudrais de l’eau.'],
  'où sont les toilettes': ['Where’s the restroom?', 'Où sont les toilettes ?'],
  'je voudrais payer par carte': ['Can I pay by card?', 'Je voudrais payer par carte.'],
  'est-ce que le service est compris': ['Is the tip included?', 'Est-ce que le service est compris ?'],
  'je dois récupérer ma voiture de location': ['I need to pick up my rental car.', 'Je dois récupérer ma voiture de location.'],
  'voici mon permis de conduire': ['Here’s my driver’s license.', 'Voici mon permis de conduire.'],
  'où est le parking': ['Where’s the parking lot?', 'Où est le parking ?'],
  'je voudrais rendre la voiture': ['I’d like to return the car.', 'Je voudrais rendre la voiture.'],
  'est-ce que l’assurance est incluse': ['Is insurance included?', 'Est-ce que l’assurance est incluse ?'],
  'j’ai besoin d’aide': ['I need help.', 'J’ai besoin d’aide.'],
  'appelez une ambulance': ['Please call an ambulance.', 'Appelez une ambulance.'],
  'je suis blessé': ['I’m hurt.', 'Je suis blessé.'],
  'je ne me sens pas bien': ['I don’t feel well.', 'Je ne me sens pas bien.'],
  'où est l’hôpital le plus proche': ['Where’s the nearest hospital?', 'Où est l’hôpital le plus proche ?'],
  'je ne comprends pas': ['I don’t understand.', 'Je ne comprends pas.'],
  'pouvez-vous répéter lentement': ['Could you repeat that slowly, please?', 'Pouvez-vous répéter lentement, s’il vous plaît ?'],
  'pouvez-vous écrire ça': ['Could you write that down, please?', 'Pouvez-vous écrire ça ?'],
  'je suis français je ne parle pas bien anglais': ['I’m French. I don’t speak English very well.', 'Je suis français, je ne parle pas bien anglais.'],
};

export const englishObjects = {
  'my son': 'mon fils', 'my daughter': 'ma fille', 'my wife': 'ma femme', 'my husband': 'mon mari', 'my child': 'mon enfant', 'my children': 'mes enfants',
  'my house': 'chez moi', house: 'maison', here: 'ici', there: 'là-bas', reservation: 'réservation', receipt: 'reçu', "driver's license": 'permis de conduire', passport: 'passeport', room: 'chambre', 'rental car': 'voiture de location', water: 'eau', check: 'addition', restroom: 'toilettes', 'parking lot': 'parking',
};

export const englishDirectPhrases = {
  'i don’t want my son in my house': 'Je ne veux pas que mon fils soit chez moi.',
  'i don’t want my daughter here': 'Je ne veux pas que ma fille soit ici.',
  'i need water': 'J’ai besoin d’eau.',
  'can i get the check': 'Puis-je avoir l’addition ?',
  'can i see your driver’s license': 'Puis-je voir votre permis de conduire ?',
  'can i see your passport': 'Puis-je voir votre passeport ?',
  'do you have a reservation': 'Avez-vous une réservation ?',
  'cash or card': 'Espèces ou carte ?',
  'would you like a receipt': 'Voulez-vous un reçu ?',
  'your card was declined': 'Votre carte a été refusée.',
  'the tip is not included': 'Le pourboire n’est pas inclus.',
  'check-in is at three': 'L’arrivée se fait à 15 h.',
  'check-out is at eleven': 'Le départ se fait à 11 h.',
  'we need your id': 'Nous avons besoin de votre pièce d’identité.',
  'the parking lot is over there': 'Le parking est là-bas.',
  'the restroom is over there': 'Les toilettes sont là-bas.',
  'please wait here': 'Veuillez attendre ici.',
  'follow me please': 'Suivez-moi, s’il vous plaît.',
};

export const offlinePhrases = Object.entries(frenchDirectPhrases).map(([french, [americanEnglishText, frenchMeaning]], index) => ({
  id: `offline-${index + 1}`,
  category: frenchObjects[french]?.category || 'general',
  frenchVariants: [french],
  americanEnglishText,
  frenchMeaning,
  keywords: french.split(' '),
  priority: 10,
}));
